### ISSUE TITLE
Organizar o projeto

### ISSUE THREAD

**Issue by vitebo** [vitebo/curso-javascript-projeto-calculadora-win#1]
# TODO

- [x] remover a pasta *node_modules*
- [x] separar o *css* do *html*
- [x] converter a indentação para 2 espaços
- [x] atualizar o *readme*
- [x] criar uma estrutura de pastas
- [x] criar um license para o projeto
- [x] criar um contributing
- [x] adicionar um editorconfig
